# Generated by Django 4.2.1 on 2023-05-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='description',
            new_name='appointment_description',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patientName',
            new_name='patient_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
