# Generated by Django 4.2.1 on 2023-05-21 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_rename_description_appointment_appointment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='account',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
