# Generated by Django 4.2.1 on 2023-05-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_group_id_appointment_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
