# Generated by Django 4.2.1 on 2023-05-26 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_appointment_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='DoctorLinksSecretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretary_id', models.CharField(max_length=40, null=True)),
                ('secretary_name', models.CharField(max_length=40, null=True)),
                ('doctor_name', models.CharField(max_length=40, null=True)),
                ('doctor_id', models.CharField(max_length=40, null=True)),
                ('account', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
