# Generated by Django 4.2.1 on 2023-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_appointment_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='secretary_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
