# Generated by Django 4.2.1 on 2023-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appointment_secretary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='secretary_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
