# Generated by Django 4.2.1 on 2023-05-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_appointment_secretary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_department',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doctorlinkssecretary',
            name='doctor_department',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
